#!/usr/bin/env bash
# Script to ping an IP address and check if the host is on the network

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
