#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID

pid_file="/var/run/myscript.pid"

# Function to clean up and terminate the script
cleanup_and_exit() {
    rm -f "$pid_file"
    echo "Terminated"
    exit 0
}

# Register cleanup_and_exit function for SIGQUIT and SIGTERM signals
trap 'cleanup_and_exit' SIGQUIT SIGTERM

# Register function for SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT

# Register function for SIGTERM signal
trap 'echo "I hate the kill command"; cleanup_and_exit' SIGTERM

# Create PID file
echo $$ > "$pid_file"
echo "To infinity and beyond"

# Infinite loop
while true; do
    sleep 2
done
