#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my_process

process_script="./manage_my_process"

start_process() {
    if [ -f "$pid_file" ]; then
        echo "$process_script is already running."
    else
        $process_script &
        echo "$process_script started"
        echo $! > "$pid_file"
    fi
}

stop_process() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill $pid
        rm -f "$pid_file"
        echo "$process_script stopped"
    else
        echo "$process_script is not running."
    fi
}

restart_process() {
    stop_process
    start_process
    echo "$process_script restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
