#!/usr/bin/env bash
#Write a Bash script that kills the process 7-highlander.
pid=$(pgrep -f "7-highlander")

# Terminate the process
if [ -n "$pid" ]; then
  kill "$pid"
else
  echo "Process not found."
fi
