#!/usr/bin/env bash
#The content of the current directory

for file in *; do
  if [ -f "$file" ] && [ ! -h "$file" ]; then
    # Extract the part of the name after the first dash
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
  fi
done
